name: CI/CD actions

on:
    push:
        branches: [main]

jobs:
    testing:
        runs-on: ubuntu-latest
        env: 
            PG_NAME: ${{ secrets.PG_NAME }}
            PG_USER: ${{ secrets.PG_USER }}
            PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
            PG_HOST: ${{ secrets.PG_HOST }}
            PG_PORT: ${{ secrets.PG_PORT }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        services:
            postgres_main:
                image: postgres:latest
                env: 
                    POSTGRES_USERS: ${{ env.PG_USER }}
                    POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
                    POSTGRES_DB: ${{ env.PG_NAME }}
                ports:
                    - 5432:5432
                options:
                    --health-cmd pg_isready
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 5                 
        steps:
            - name: Проверить изменения
              uses: actions/checkout@v2

            - name: Установка Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12

            - name: Установка зависимостей
              run: pip install -r requirements.txt

            - name: Линтер
              run: flake8 django-crud --exclude migrations --ignore E501,F401,E302,E902,W391,W292
            
            - name: Тесты
              run: python ./manage.py test
              env: 
                PG_NAME: ${{env.PG_NAME}}
                PG_USER: ${{env.PG_USER}}
                PG_PASSWORD: ${{env.PG_PASSWORD}}
                PG_HOST: ${{env.PG_HOST}}
                PG_PORT: ${{env.PG_PORT}}

    deploy:
      runs-on: ubuntu-latest
      needs: testing
      steps:
        - name: Деплой
          uses: appleboy/ssh-action@master
          with:
            host: ${{env.SSH_HOST}}
            username: ${{env.SSH_PASSWORD}}
            password: ${{env.SSH_USERNAME}}
            script: |
              cd django-crud/
              git pull
              sudo systemctl restart gunicorn




